spring.application.name=foodservice-backend

#spring.datasource.url=jdbc:postgresql://localhost:5433/SprintProject
#spring.datasource.driverClassName=org.postgresql.Driver
#spring.datasource.username=postgres
#spring.datasource.password=Kuldeep@16


spring.datasource.url=jdbc:postgresql://172.16.14.101:5433/foodservice
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgre
spring.datasource.password=dks2004



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
springdoc.swagger-ui.path=/swagger-ui.html
